import Head from "next/head";
import { startOfMonth, endOfMonth, subMonths } from "date-fns";
import type { NextPage } from "next";
import useTotals from "./useTotals";
import * as d3 from "d3";
import Calendar from "./Calendar";

const Home: NextPage = () => {
  const [totals, dates, setDates] = useTotals();
  const now = Date.now();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button
          onClick={() => {
            setDates({
              start_date: startOfMonth(subMonths(now, 1)),
              end_date: endOfMonth(subMonths(now, 1)),
            });
          }}
        >
          Last Month
        </button>
        <button
          onClick={() => {
            setDates({
              start_date: startOfMonth(now),
              end_date: endOfMonth(now),
            });
          }}
        >
          This Month
        </button>
      </main>
      <section>
        <h3>Hours</h3>
        <table>
          <tr>
            <th>Expected</th>
            <td>{(d3.sum(totals, (t) => t.expected) / 3600).toFixed(2)}</td>
          </tr>
          <tr>
            <th>Logged</th>
            <td>{(d3.sum(totals, (t) => t.logged) / 3600).toFixed(2)}</td>
          </tr>
          <tr>
            <th>Balance</th>
            <td>{(d3.sum(totals, (t) => t.balance) / 3600).toFixed(2)}</td>
          </tr>
        </table>
        <hr />
      </section>
      {dates?.start_date && dates?.end_date && (
        <Calendar
          entries={totals}
          startDate={dates.start_date}
          endDate={dates.end_date}
        />
      )}
      <section id="chart"></section>
    </div>
  );
};

export default Home;
